name: 'Deploy infra'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./infra/requirements/requirements.txt

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./app
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.python.version=3
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=src
            -Dsonar.tests=tests

  deploy-infra:
    runs-on: ubuntu-latest
    needs: code-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Init
        run: terraform init
        working-directory: './infra/'

      - name: Validate
        run: terraform validate
        working-directory: './infra/'

      - name: Plan
        run: terraform plan
        working-directory: './infra/'

      - name: Apply
        run: terraform apply -auto-approve
        working-directory: './infra/'
